version: '3'

services:
  terra-fullnode:
    image: localhost/gaia:latest
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file: .env
    ports:
      - 26656:26656
      - 26657:26657
    # In order to persist data
    #volumes:
    #  - /opt/gaiafnd/data:/gaia/.gaia