version: '3'

services:
  terra-fullnode:
    image: prism-finance/terrapatched:v2.1.4
    restart: always
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    env_file: .env
    ports:
      - 26656:26656
      - 26657:26657
    #In order to persist data
    volumes:
      - /opt/terrafnd/data:/terra/.terra